project:
  type: website

website:
  title: "E177: Mechanical Design"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ideation/index.qmd
        text: Ideation/Project Background
      - href: design_calc_sim/index.qmd
        text: Design & Simulation
      - href: manufacturing/index.qmd
        text: Manufacturing
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true